# Generated by Django 5.2.5 on 2025-08-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_brand_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
