# Generated by Django 5.2.5 on 2025-08-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('warehouse_id', models.CharField(choices=[('ChW001', 'ChW001'), ('TUW002', 'TUW002'), ('QRW003', 'QRW003'), ('UAEW04', 'UAEW04'), ('USAW05', 'USAW05'), ('BAW006', 'BAW006')], max_length=10, unique=True)),
            ],
        ),
    ]
