# Generated by Django 5.2.5 on 2025-08-31 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit_number', models.CharField(max_length=50)),
                ('tracking_number', models.CharField(max_length=50)),
                ('shipping_company', models.CharField(max_length=100)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('package_type', models.CharField(max_length=50)),
                ('arrival_date', models.DateField()),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.warehouse')),
            ],
        ),
    ]
